version: '3.8'

services: 
  mysqldb:
    image: mysql
    restart: always
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    ports:
      - "3306:3306"
    
    
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: ./.env
    ports:
      - "3000:3000"
    volumes: 
      - .:/app
      - /app/node_modules
    depends_on:
      - mysqldb
    command: ["./wait-for-it.sh", "-t", "300", "mysqldb:3306", "--", "npm", "start"]
    stdin_open: true
    tty: true

